AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  Proyecto SAM con AWS Step Functions y Lambdas en Node.js 20.x con TypeScript
Globals:
  Function:
    Runtime: provided.al2
    Timeout: 30
    Architectures:
      - arm64
    Layers:
      - arn:aws:lambda:us-east-1:529202746267:layer:bun:1
      - !Ref UtilsLayer
  Api:
    OpenApiVersion: 3.0.1
Resources:
  UtilsLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: "esnext"
        Sourcemap: true
        Platform: node # Aunque usamos bun, esbuild necesita una plataforma conocida
        Format: esm
        OutExtension:
          - '.js=.js'
    Properties:
      LayerName: !Sub ${AWS::StackName}-utils
      Description: Layer containing utils package
      ContentUri: ../../packages/utils
      CompatibleRuntimes:
        - provided.al2
      RetentionPolicy: Retain
      ContentBasedHash: true

  ScarletExecutionQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${AWS::StackName}-execution-queue
      VisibilityTimeout: 900 # 15 minutos para procesar mensajes
      MessageRetentionPeriod: 1209600 # 14 días
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ScarletExecutionDLQ.Arn
        maxReceiveCount: 3

  ScarletExecutionDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${AWS::StackName}-execution-dlq
      MessageRetentionPeriod: 1209600 # 14 días

  ScarletStorageBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      BucketName: !Sub ${AWS::StackName}-scarlet-storage
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldFiles
            Status: Enabled
            ExpirationInDays: 30
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      EndpointConfiguration: REGIONAL
      DefinitionBody:
        openapi: 3.0.1
        info:
          title: Scarlett API
          version: "1.0"
        x-amazon-apigateway-binary-media-types:
          - multipart/form-data
        paths:
          /validate-session:
            post:
              x-amazon-apigateway-integration:
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ValidateSessionFunction.Arn}/invocations
                passthroughBehavior: when_no_match
                httpMethod: POST
                type: aws_proxy
              responses:
                "200":
                  description: Success
              x-amazon-apigateway-cors:
                allowOrigin: "'*'"
                allowMethods:
                  - POST
                  - OPTIONS
                allowHeaders:
                  - Content-Type
                  - Authorization
                  - X-Amz-Date
                  - X-Api-Key
                  - X-Amz-Security-Token
                maxAge: 300
          /execution:
            post:
              x-amazon-apigateway-integration:
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ValidateSessionFunction.Arn}/invocations
                passthroughBehavior: when_no_match
                httpMethod: POST
                type: aws_proxy
              responses:
                "200":
                  description: Success
              x-amazon-apigateway-cors:
                allowOrigin: "'*'"
                allowMethods:
                  - POST
                  - OPTIONS
                allowHeaders:
                  - Content-Type
                  - Authorization
                  - X-Amz-Date
                  - X-Api-Key
                  - X-Amz-Security-Token
                maxAge: 300
          /get-upload-url:
            post:
              security: [] # This explicitly makes the endpoint public (no auth required)
              x-amazon-apigateway-integration:
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetUploadUrl.Arn}/invocations
                passthroughBehavior: when_no_match
                httpMethod: POST
                type: aws_proxy
              responses:
                "200":
                  description: Success
              x-amazon-apigateway-cors:
                allowOrigin: "'*'"
                allowMethods:
                  - POST
                  - OPTIONS
                allowHeaders:
                  - Content-Type
                  - Authorization
                  - X-Amz-Date
                  - X-Api-Key
                  - X-Amz-Security-Token
                maxAge: 300
          /download-template:
            get:
              security: [] # This explicitly makes the endpoint public (no auth required)
              x-amazon-apigateway-integration:
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DownloadTemplate.Arn}/invocations
                passthroughBehavior: when_no_match
                httpMethod: GET
                type: aws_proxy
              responses:
                "200":
                  description: Success
              x-amazon-apigateway-cors:
                allowOrigin: "'*'"
                allowMethods:
                  - GET
                  - OPTIONS
                allowHeaders:
                  - Content-Type
                  - Authorization
                  - X-Amz-Date
                  - X-Api-Key
                  - X-Amz-Security-Token
                maxAge: 300
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
  ValidateSessionFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - src/validate-session.ts
        Bundle: true
        Minify: true
        Format: esm
        Platform: node
        Target: esnext
        External:
          - "@aws-sdk/client-sqs"
          - "@aws-sdk/*"
          - aws-sdk
          - "@forge/api"
          - bun
          - bun:*
        Define:
          "process.env.BUN_RUNTIME": "true"
        Packages: "external"
        NodeModules: ["*"]
        Alias:
          utils: ../../packages/utils/src
        MainFields:
          - module
          - main
        OutExtension:
          - ".js=.mjs"
        Banner:
          js: "import { createRequire } from 'module';const require = createRequire(import.meta.url);"
    Properties:
      Environment:
        Variables:
          SQS_QUEUE_URL: !Ref ScarletExecutionQueue
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt ScarletExecutionQueue.QueueName
        - AWSLambdaBasicExecutionRole
      Handler: validate-session.post
      CodeUri: ./src
      Events:
        ApiPOSTexecution:
          Type: Api
          Properties:
            Path: /execution
            Method: POST
            RestApiId: !Ref Api
  OperationsQueue:
    Type: AWS::SQS::Queue
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      QueueName: scarlet-operations-queue
      MessageRetentionPeriod: 1209600 # 14 días en segundos
  ScarletMappingFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - src/scarlet-mapping.mts
        Bundle: true
        Minify: true
        Format: esm
        Platform: node
        Target: esnext
        External:
          - "@aws-sdk/*"
          - aws-sdk
          - "@forge/api"
          - date-fns
          - jose
          - uuid
          - bun
        TreeShaking: true
        Sourcemap: false

    Properties:
      Handler: scarlet-mapping.handler
      CodeUri: ./
      Policies:
        - AWSLambdaBasicExecutionRole
        - S3CrudPolicy:
            BucketName: !Ref ScarletStorageBucket
  GetExistingIssuesFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - src/get-existing-issues.mts
        Bundle: true
        Minify: true
        Format: esm
        Platform: node
        Target: esnext
        External:
          - "@aws-sdk/*"
          - aws-sdk
          - "@forge/api"
          - date-fns
          - jose
          - uuid
          - bun
        TreeShaking: true
        Sourcemap: false

    Properties:
      Handler: get-existing-issues.handler
      CodeUri: ./
      Policies:
        - AWSLambdaBasicExecutionRole
        - S3CrudPolicy:
            BucketName: !Ref ScarletStorageBucket
  SaveStorage:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - src/save-storage.mts
        Bundle: true
        Minify: true
        Format: esm
        Platform: node
        Target: esnext
        External:
          - "@aws-sdk/*"
          - aws-sdk
          - "@forge/api"
          - date-fns
          - jose
          - uuid
          - bun
        TreeShaking: true
        Sourcemap: false

    Properties:
      Handler: save-storage.handler
      CodeUri: ./
      Policies:
        - AWSLambdaBasicExecutionRole
        - S3CrudPolicy:
            BucketName: !Ref ScarletStorageBucket
      Events:
        ApiGETexecutionid:
          Type: Api
          Properties:
            Path: /execution/{id}
            Method: GET
            RestApiId: !Ref Api
  ExecutionPipe:
    Type: AWS::Pipes::Pipe
    DependsOn: []
    Properties:
      RoleArn: !GetAtt StateMachineExecutionRole.Arn
      Name: scarlet-execution-pipe
      DesiredState: RUNNING
      Source: !GetAtt ScarletExecutionQueue.Arn
      SourceParameters:
        SqsQueueParameters:
          BatchSize: 1
      TargetParameters:
        StepFunctionStateMachineParameters:
          InvocationType: FIRE_AND_FORGET
      Target: !GetAtt StateMachine.Arn
  # Máquina de estado (Step Functions) definida en un archivo JSON externo
  StateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionSubstitutions:
        ValidateSessionFunction: !GetAtt ValidateSessionFunction.Arn
        ScarletMappingFunction: !GetAtt ScarletMappingFunction.Arn
        GetExistingIssuesFunction: !GetAtt GetExistingIssuesFunction.Arn
        SaveStorage: !GetAtt SaveStorage.Arn
        OperationsQueue: !GetAtt OperationsQueue.Arn
        AddOrderFunction: !Ref AWS::NoValue
      Role: !GetAtt StateMachineExecutionRole.Arn
      Name: scarlet-execution-machine
      DefinitionUri: statemachine.json

  # Rol de ejecución para la máquina de estado
  StateMachineExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - states.amazonaws.com
                - pipes.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: StepFunctionsExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                  - sqs:SendMessage
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - states:StartExecution
                Resource: "*"
  ValidateSessionFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      TargetFunctionArn: !GetAtt ValidateSessionFunction.Arn
      AuthType: AWS_IAM
  GetUploadUrl:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: GetUploadUrl
      Handler: get-upload-url.post
      CodeUri: ./src
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
              Resource: !Sub arn:aws:s3:::${AWS::StackName}-scarlet-storage/*
      Events:
        ApiPOSTgetuploadurl:
          Type: Api
          Properties:
            Path: /get-upload-url
            Method: POST
            RestApiId: !Ref Api
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - get-upload-url.ts
        Bundle: true
        Minify: true
        Format: esm
        Platform: node
        Target: esnext
        External:
          - "@aws-sdk/*"
          - aws-sdk
          - "@forge/api"
          - date-fns
          - jose
          - uuid
          - bun
        TreeShaking: true
        Sourcemap: false
  GetUploadUrlLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      LogGroupName: !Sub /aws/lambda/${GetUploadUrl}
  DownloadTemplate:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: DownloadTemplate
      Handler: download-template.get
      CodeUri: ./src
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Events:
        ApiGETdownloadtemplate:
          Type: Api
          Properties:
            Path: /download-template
            Method: GET
            RestApiId: !Ref Api
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - download-template.ts
        Bundle: true
        Minify: true
        Format: esm
        Platform: node
        Target: esnext
        External:
          - bun
        TreeShaking: true
        Sourcemap: false

Outputs:
  ExecutionTriggerUrl:
    Description: Scarlet Execution Trigger Url
    Value: !GetAtt ValidateSessionFunctionUrl.FunctionUrl
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub https://${Api}.execute-api.${AWS::Region}.amazonaws.com/Prod/
